### ISSUE TITLE
"Failed to execute 'remove' on 'DOMTokenList'" error occurs in navbar when beforeDestroy is executed

### ISSUE THREAD

**Issue by kirillsun1** [buefy/buefy#2160]
Buefy version: [0.8.10]
Vuejs version: [2.6.11]
OS/Browser: Mac OS/Google Chrome (Version 79.0.3945.117), Safari (Version 13.0.4 (15608.4.9.1.3)

**Description**
After updating to Buefy 0.8.10 I started to get the following errors:

In Chrome:
```
DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at VueComponent.removeBodyClass (webpack-internal:///./node_modules/buefy/dist/esm/navbar.js:316:33)
    at VueComponent.beforeDestroy (webpack-internal:///./node_modules/buefy/dist/esm/navbar.js:398:10)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1853:57)
    at callHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4213:7)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3972:5)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3156:27)
    at invokeDestroyHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6104:59)
    at VueComponent.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6457:30)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3995:8)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3156:27)
```

In Safari:
```
SyntaxError: The string did not match the expected pattern.
(anonymous function) — main.ts:66
globalHandleError — vue.runtime.esm.js:1870
handleError — vue.runtime.esm.js:1839
invokeWithErrorHandling — vue.runtime.esm.js:1862
callHook — vue.runtime.esm.js:4219
(anonymous function) — vue.runtime.esm.js:3978
destroy — vue.runtime.esm.js:3159
invokeDestroyHook — vue.runtime.esm.js:6114
patch — vue.runtime.esm.js:6467
(anonymous function) — vue.runtime.esm.js:4001
destroy — vue.runtime.esm.js:3159
invokeDestroyHook — vue.runtime.esm.js:6114
invokeDestroyHook — vue.runtime.esm.js:6119
patch — vue.runtime.esm.js:6467
(anonymous function) — vue.runtime.esm.js:4001
destroy — vue.runtime.esm.js:3159
invokeDestroyHook — vue.runtime.esm.js:6114
patch — vue.runtime.esm.js:6467
(anonymous function) — vue.runtime.esm.js:4001
destroy — vue.runtime.esm.js:3159
invokeDestroyHook — vue.runtime.esm.js:6114
removeVnodes — vue.runtime.esm.js:6130
updateChildren — vue.runtime.esm.js:6235
patchVnode — vue.runtime.esm.js:6319
patch — vue.runtime.esm.js:6482
(anonymous function) — vue.runtime.esm.js:3948
updateComponent — vue.runtime.esm.js:4066
get — vue.runtime.esm.js:4479
run — vue.runtime.esm.js:4554
flushSchedulerQueue — vue.runtime.esm.js:4310
(anonymous function) — vue.runtime.esm.js:1980
flushCallbacks — vue.runtime.esm.js:1906
promiseReactionJob
window.document.body.classList.remove("")
```

After some debugging it turned out that the error comes from beforeDestroy method in b-navbar component:
<img width="1440" alt="Screenshot 2020-01-22 at 14 21 13" src="https://user-images.githubusercontent.com/24778299/72893743-7b989100-3d22-11ea-868e-bebbf3bfe110.png">

The `removeBodyClass` method basically just calls `document.body.classList.remove(className)`.
Back to beforeDestroy method: If both `fixedTop` and `fixedBottom` properties of navbar have values false, then the variable `className` value is empty string, what causes an error in `removeBodyClass` method.

**Steps to reproduce**
1. Add navbar to some component and make it be conditionally rendered (using v-if). Do not use `fixedTop` or `fixedBottom` properties.
```
<b-navbar v-if="shownavnar" />
``` 
2. Change the condition to hide the navbar.
3. Navbar `beforeDestroy` method should be called and then error happens. See it in console.

**Comment by kirillsun1** [comment]
Hey

I haven't found any bug template here. If there is one, please let me know, I will adjust the description.

**Comment by superbiche** [comment]
Same issue with Buefy 0.8.10. I was upgrading from 0.8.8, just downgrading to 0.8.9 fixed it for now.

**Comment by cain** [comment]
Thanks for fixing!

**Comment by geilix10** [comment]
Still not fixed using nuxt-buefy `0.3.21`
Any idea?

**Comment by jtommy** [comment]
I have to make a new release yet

**Comment by geilix10** [comment]
> I have to make a new release yet

Can you push this thread when the release is done?

**Comment by abinhho** [comment]
https://github.com/buefy/buefy/blob/ba357b801d73b54a75a6c861a2fe2d3320e6c148/src/components/navbar/Navbar.vue

```
beforeDestroy() {
        let className = ''
        if (this.fixedTop) {
            className = this.spaced
                ? BODY_SPACED_FIXED_TOP_CLASS : BODY_FIXED_TOP_CLASS
        } else if (this.fixedBottom) {
            className = this.spaced
                ? BODY_SPACED_FIXED_BOTTOM_CLASS : BODY_FIXED_BOTTOM_CLASS
        }
        this.removeBodyClass(className)
    },
```
should be 
```
beforeDestroy() {
        let className = ''
        if (this.fixedTop) {
            className = this.spaced
                ? BODY_SPACED_FIXED_TOP_CLASS : BODY_FIXED_TOP_CLASS
        } else if (this.fixedBottom) {
            className = this.spaced
                ? BODY_SPACED_FIXED_BOTTOM_CLASS : BODY_FIXED_BOTTOM_CLASS
        }
        if (className) {
              this.removeBodyClass(className)
       }
    },
```

**Comment by jtommy** [comment]
@abinhho https://github.com/buefy/buefy/blob/dev/src/components/navbar/Navbar.vue is the last version

**Comment by abinhho** [comment]
@jtommy But it's still not released? I check some recent versions but not fixed yet.

**Comment by jtommy** [comment]
No at the moment

**Comment by abinhho** [comment]
So, I temporary fix by:
```
body {
    &.has-navbar-fixed-top {
        padding-top: 0;
    }
}
.navbar {
    &.is-fixed-top {
        top: initial;
        position: relative;
    }
}
```

And added
```
<b-navbar
      :fixed-top="true" <-- this option
```

Waiting for new release ❤️
