### ISSUE TITLE
Numberinput: e.toFixed is not a function

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#3260]
### Overview of the problem

**Buefy** version: 0.9.5
**OS/Browser**: Facebook 301.0.0 (in-app browser), iOS 2.5.1

### Description

```
TypeError: e.toFixed is not a function. (In 'e.toFixed(this.stepDecimals)', 'e.toFixed' is undefined)
  at increment(/_nuxt/da83da5.js:1:336404)
  at increment([native code])
  at longPressTick(/_nuxt/da83da5.js:1:336580)
  at longPressTick([native code])
  at onStartLongPress(/_nuxt/da83da5.js:1:336849)
  at onStartLongPress([native code])
  at te(/_nuxt/0298e78.js:1:11753)
  at c(/_nuxt/da83da5.js:1:33111)
```

### Steps to reproduce

1. Input `0e2`
2. Press button to increment

**Comment by ronnyvdweyer** [comment]
Same problem over here, i update to version 0.9.13
but this did not help.  
When you click first the - and then + it works. when you start with the + gives an error.

```
TypeError: e.toFixed is not a function
    at a.increment (buefy.min.js)
    at a.longPressTick (buefy.min.js)
    at a.onStartLongPress (buefy.min.js)
 ...
```
