### ISSUE TITLE
problem testing custom build after cloning dev branch

### ISSUE THREAD

**Issue by nikugogoi** [buefy/buefy#738]
### Overview of the problem

**Buefy** version: 0.6.5
**Vuejs** version: 2.5.16
**OS/Browser**: Linux, Node v8.9.4

### Description

I am trying to make some changes to your repo. So for testing my changes I tried to use the cloned repo in my project. I did not make any changes but still there is an error.

### Steps to reproduce

1. after cloning run `yarn`
2. run `yarn build`
3. run `yarn link`
4. in the local project run `yarn link 'buefy'`
5. compiling the project shows error (in my case I use NUXT, running `yarn dev` shows error)

### Error outcome

```
Module build failed: Error: Cannot find module 'eslint-config-buefy'
Referenced from: /home/dev-11/module-tester/buefy/.eslintrc.js
    at ModuleResolver.resolve (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config/config-file.js:471:25)
    at load (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config/config-file.js:542:26)
    at configExtends.reduceRight (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config.js:180:43)
    at Config.getConfigVector (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config.js:287:21)
    at Config.getConfig (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/config.js:330:29)
    at processText (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/cli-engine.js:162:33)
    at CLIEngine.executeOnText (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint/lib/cli-engine.js:618:17)
    at lint (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/home/dev-11/nuxt/pupnpaws-web-SPA/node_modules/eslint-loader/index.js:213:21)
```

**Comment by anteriovieira** [comment]
Hi @nikugogoi  I could not reproduce the error, it worked for me here.

**Comment by anteriovieira** [comment]
You could try again, this seems to be an installation failure.

**Comment by nikugogoi** [comment]
I tried again.... Could you tell me exactly how we can test the changes we make to the project. I seem to have missed out on the contributing guidelines. 
when I run `yarn build` in your project the lib directory is successfuly created. Then for testing these changes I link this package to the project where I am using buefy. But then the project throws errors during build.
P.S. I am trying this with a frsh clone of the project

**Comment by anteriovieira** [comment]
> when I run yarn build in your project the lib directory is successfuly created. Then for testing these changes I link this package to the project where I am using buefy.

I followed the steps and it worked for me. I'll try again later.

> Could you tell me exactly how we can test the changes we make to the project.

You can use the `* .spec` files to build the tests, then just run `npm run test` (you should have the minimum of test knowledge to edit spec files).

**Comment by anteriovieira** [comment]
@nikugogoi did you have any progress?

**Comment by service-paradis** [comment]
@jtommy 
I think this issue can be closed?
